name: CI pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  
jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do node.jobs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
        
      - name: Instalar dependencias
        run: npm ci 

      - name: Gerar prisma client
        run: npx prisma generate

      - name: Checagem de tipos
        run: npx tsc --noEmit
      
      - name: Linter
        run: npm run lint

      - name: Testes E2E
        run: npm run test:e2e
